version: "3.0"

services:
  etcd:
    image: quay.io/coreos/etcd:v2.3.8
    command: >-
          -name etcd0
          --data-dir /etcd_data
          -advertise-client-urls http://etcd:2379,http://etcd:4001
          -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
          -initial-advertise-peer-urls http://etcd:2380
          -listen-peer-urls http://0.0.0.0:2380
          -initial-cluster-token etcd-cluster-1
          -initial-cluster etcd0=http://etcd:2380
          -initial-cluster-state new
    volumes:
      - etcd:/etcd_data
      - /usr/share/ca-certificates/:/etc/ssl/certs
    ports:
      - 0.0.0.0:2379:2379

  ui:
    image: buddho/etcd-browser
    environment:
      ETCD_HOST: etcd
      ETCD_PORT: 2379
    ports:
      - 0.0.0.0:2888:8000

  gui:
    build:
      context: .
      dockerfile: Dockerfile
    image: metacoma/silverkey-golang-client:latest
    environment:
      - DISPLAY
      - SILVERKEY_HOST
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      # required to run gui from non-root user inside a docker container
      # not supported yet
      # - "/etc/group:/etc/group:ro"
      # - "/etc/passwd:/etc/passwd:ro"
      # - "/etc/shadow:/etc/shadow:ro"
      # - "/etc/sudoers.d:/etc/sudoers.d:ro"

networks:
  silverkey:

volumes:
  etcd:
